/* ================= BOSS SPRITES =================
   บอสประจำสัปดาห์ — พิกเซลอาร์ต 24×24 สไตล์เดียวกับตัววิ่ง
   ใช้ร่วมกันทั้งหน้าเกม (index.html) และหน้า admin (admin.html)
   ตัวอักษรในกริด = สีในพาเลต · "." = โปร่ง · "O" = เส้นขอบ
   anim = ตัวอักษรที่จะถูกจับกลุ่มแยกไว้ขยับ (ปีก / ZZZ / เปลว) */
const BOSS_SKINS = [
  { k:"dragon", n:"มังกรผัดวันประกันพรุ่ง", e:"🐉", anim:"Hh",
    pal:{B:"#4cc96a", b:"#22803a", Y:"#ffe08a", H:"#b04cff", h:"#6b1fb0", R:"#ff3b5c", E:"#ffea00", W:"#ffffff"},
    g:[
    "........................",
    "..OO...Ob......bO..OO...",
    ".OHHO..ObO....ObO.OHHO..",
    ".OHHHO..OOBBBBOO.OHHHO..",
    ".OHHHHO.OBBBBBBO.OHHHHO.",
    "..OHHHHOBBBBBBBBOHHHHO..",
    "..OHHHHOBBEBBBEBOHHHHO..",
    "...OHHHOBBEBBBEBOHHHO...",
    "...OHHOBBBBBBBBBBOHHO...",
    "....OOBBWBWBWBWBBBOO....",
    ".....OBBRRRRRRRRBBO.....",
    ".....OBBBBBBBBBBBBO.....",
    "....OBBBBYYYYYYBBBBO....",
    "...OBBBBYYYYYYYYBBBBO...",
    "...OBBBBYYYYYYYYBBBBO...",
    "...OBBBBYYYYYYYYBBBBO...",
    "....OBBBBYYYYYYBBBBO....",
    ".....OBBBBBBBBBBBBO.OO..",
    "....OBBOOBBBBBBOOBBOBBO.",
    "....OBBO.OBBBBO..OBBBBO.",
    "....OOO..OBBBBO...OBBO..",
    ".........OOOOOO....OO...",
    "........................",
    "........................"]},
  { k:"ogre", n:"ยักษ์ขี้เกียจ", e:"👹", anim:"Z",
    pal:{S:"#e8734a", s:"#a8452a", K:"#5a3d2b", E:"#ffffff", T:"#ffe9c4", C:"#3b6ea5", Z:"#ffd23f"},
    g:[
    "..................ZZ....",
    "..OTO......OTO...Z......",
    "..OTOOOOOOOOTO...ZZZ....",
    "..OKKKKKKKKKKO..........",
    ".OKKSSSSSSSSKKO.........",
    ".OKSSSSSSSSSSKO.........",
    ".OSSEESSSSEESSO.........",
    ".OSSOOSSSSOOSSO.........",
    ".OSSSSSSSSSSSSO...OO....",
    ".OSSSsssssssSSO..OKKO...",
    "..OSTSSSSSSTSO...OKKO...",
    "..OOOSSSSSSOOO...OKKO...",
    ".OSSSOOOOOOSSSOOOOKKO...",
    "OSSSSSSSSSSSSSSSSKKKO...",
    "OSSSSSSSSSSSSSSSSOKO....",
    "OSSSSSSSSSSSSSSSSOO.....",
    ".OSSSSSSSSSSSSSSO.......",
    "..OCCCCCCCCCCCCO........",
    "..OCCCCCOOCCCCCO........",
    "..OCCCCO..OCCCCO........",
    "..OCCCCO..OCCCCO........",
    ".OKKKKKO..OKKKKKO.......",
    ".OOOOOOO..OOOOOOO.......",
    "........................"]},
  { k:"ghost", n:"ผีเลื่อนโพสต์", e:"👻", anim:"",
    pal:{G:"#dfe9ff", g:"#9fb3e6", E:"#0b0316", M:"#5c2bd6"},
    g:[
    "........................",
    "........OOOOOOOO........",
    "......OOGGGGGGGGOO......",
    ".....OGGGGGGGGGGGGO.....",
    "....OGGGGGGGGGGGGGGO....",
    "....OGGGGGGGGGGGGGGO....",
    "...OGGGEEGGGGGGEEGGGO...",
    "...OGGGEEGGGGGGEEGGGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OGGGGGGGMMMMGGGGGO...",
    "...OGGGGGGMMMMMMGGGGO...",
    "...OGGGGGGGMMMMGGGGGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OGgGGGGGGGGGGGGgGO...",
    "...OGgGGGGgGGGGgGGgGO...",
    "...OGggGGGggGGgggGggO...",
    "...OGgGOGgggOGgggOGgO...",
    "...OgGO.OggO.OggO.OgO...",
    "...OOO...OO...OO...OO...",
    "........................",
    "........................",
    "........................"]},
  { k:"robot", n:"จอมอัลกอริทึม", e:"🤖", anim:"AZSKC",
    pal:{M:"#9aa7b8", m:"#5b6675", E:"#ff3b5c", e:"#7a3a4a", Q:"#4ee1ff", q:"#2a6a7a", A:"#ffd23f", Z:"#ffffff", S:"#ffee88", K:"#8a8f9c",
         T:"#b8742e", t:"#6e3f16", Y:"#ffd23f", y:"#d19a12", C:"#fff6b0"},
    /* เปลี่ยนท่าตามเลือดที่เหลือ · dead = หุ่นพังกอง + หีบสมบัติเปิด */
    phases:[
      { min:.75, t:"💤 ร่าง 1 · โหมดประหยัดพลังงาน", g:    [
    "...........OO....ZZZZ...",
    "...........OmO.....Z....",
    "...........OO....ZZZZ...",
    "......OOOOOOOOOOOO......",
    ".....OMMMMMMMMMMMMO..ZZ.",
    "....OMMmmmmmmmmmmMMO.Z..",
    "....OMMmmmmmmmmmmMMO....",
    "....OMMmeeemmeeemMMO....",
    "....OMMmmmmmmmmmmMMO....",
    "....OMMmqqqqqqqqmMMO....",
    ".....OMMMMMMMMMMMMO.....",
    "......OOOOOMMOOOOO......",
    "..OOO....OMMMMO....OOO..",
    ".OMMMOOOOMMMMMMOOOOMMMO.",
    ".OMMMMMMMMQQMMMMMMMMMMO.",
    ".OMMMOOMMMMQQMMMMOOMMMO.",
    ".OMMMO.OMMMMMMMMO.OMMMO.",
    ".OMMMO.OMMmmmmMMO.OMMMO.",
    ".OOOO..OMMMMMMMMO..OOOO.",
    ".......OMMMOOMMMO.......",
    "......OMMMO..OMMMO......",
    "......OMMMO..OMMMO......",
    "......OOOOO..OOOOO......",
    "........................"] },
      { min:.5,  t:"😠 ร่าง 2 · ระบบตื่น ประมวลผลหนัก", g:    [
    "...........OO...........",
    "...........OAO..........",
    "...........OO...........",
    "......OOOOOOOOOOOO......",
    ".....OMMMMMMMMMMMMO.....",
    "....OMMOOOmmmmOOOMMO....",
    "....OMMmEEEmmEEEmMMO....",
    "....OMMmmEEmmEEmmMMO....",
    "..S.OMMmmmmmmmmmmMMO.S..",
    "....OMMmmQmQmQmQmMMO....",
    ".S...OMMMMMMMMMMMMO...S.",
    "SS....OOOOOMMOOOOO....SS",
    "..OOO....OMMMMO....OOO..",
    ".OMMMOOOOMMMMMMOOOOMMMO.",
    ".OMMMMMMMMQQMMMMMMMMMMO.",
    ".OMMMOOMMMMQQMMMMOOMMMO.",
    ".OMMMO.OMMMMMMMMO.OMMMO.",
    ".OMMMO.OMMmmmmMMO.OMMMO.",
    ".OOOO..OMMMMMMMMO..OOOO.",
    ".......OMMMOOMMMO.......",
    "......OMMMO..OMMMO......",
    "......OMMMO..OMMMO......",
    "......OOOOO..OOOOO......",
    "........................"] },
      { min:.25, t:"⚡ ร่าง 3 · ระบบรวน ตาข้างเดียวดับ", g:    [
    "...........OOS..........",
    "...........OmO.S........",
    "...........OO...........",
    "......OOOOOOOOOOOO......",
    ".....OMMMMMMMMOMMMO.....",
    "....OMMmmmmmmOmmmMMO....",
    "....OMMmEEEmmmOmmMMO....",
    "....OMMmEEEmmOmmmMMO....",
    "....OMMmmmmmmmOmmMMO....",
    "....OMMmQQmmQQmmmMMO....",
    ".....OMMMMMMMMMMMMO.....",
    "......OOOOOMMOOOOO......",
    ".SOOO....OMMMMO....SOO..",
    ".OMMMOOOOMMMMMMOOOOMMMO.",
    ".OMSMMMMMMQQMMMMMMMMMMO.",
    ".OOMMOOMMMMQQMMMMOOMMSO.",
    ".OMOMO.OMMMMMMMMO.OMMMO.",
    ".OMMMO.OMMmmmmMMO.OMMMO.",
    ".OOOO..OMMMMMMMMO..OOOO.",
    ".......OMMSOOMMMO.......",
    "......OMMMO..OMMMO......",
    "......OMMMO..OMMMO......",
    "......OOOOO..OOOOO......",
    "........................"] },
      { min:0,   t:"🔥 ร่าง 4 · เกือบพัง ควันขึ้น", g:    [
    "...........KOKK.........",
    "..........KOmOK.........",
    "...........OK...........",
    "......OOOOOOOOOOOO......",
    ".....OMMMMMMMMMMMMO.....",
    "....OMMmEmEmmEmEmMMO....",
    "....OMMmmEmmmmEmmMMO....",
    "....OMMmEmEmmEmEmMMO....",
    "....OMMmmmmmmmmmmMMO....",
    "....OMMmEEEEEEEEmMMO....",
    ".....OMMMMMMMMMMMMO.....",
    "......OOOOOMMOOOOO......",
    "..OOO....OMMMMO....OOO..",
    ".OSMMOOOOMMMMMMOOOOMSMO.",
    ".OMMMMMMMMQQMMMMMMMMMMO.",
    ".OMMMOOMMMOQQMMMMOOMMMO.",
    ".OMOMO.OMMMOMMMMO.OOMMMO",
    ".OMMOO.OMMmmmmMMO.OO..O.",
    ".OOOO..OMMMMMMMMO..OOOO.",
    ".......OMMMOOMMMO...S...",
    "......OMMMO..OMMMO......",
    "......OMMMO..OMMMO....S.",
    "......OOOOO..OOOOO......",
    "........................"] }],
    dead:    [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "................C.......",
    "...............CCC...C..",
    "................C.......",
    "........................",
    ".....................yY.",
    "..............OOOOOOO...",
    ".....K.......OtttttttO..",
    "...K..S......tTTTTTTTtO.",
    "..K..........tTTTYTTTtO.",
    "....S........OOOOOOOOOO.",
    ".OOOOOOOOS...YCYyYYCyYOC",
    "OMMMMMMMMO...YYyYYYyYYO.",
    "OMEmmEmMMO...OOOOOOOOOO.",
    "OMmEEmmMMOOO.TTTTTTTTTO.",
    "OMEmmEmMMOOAOYYYYOYYYYO.",
    "OMMEEEEMMOOO.TTTOYOTTTO.",
    "OMMMMMMMMOOMMMOTTTTTTTO.",
    ".OOOOOOOOOMOMMMOOOOOOOO.",
    "........................"] },
  { k:"slime", n:"สไลม์ขี้เกียจ", e:"🟢", anim:"ZSDC",
    pal:{G:"#8ee86a", g:"#4fae4a", L:"#e4ffd0", E:"#1a0b2e", W:"#ffffff", P:"#ff8fb0", M:"#7a1030", D:"#7fd8ff", Z:"#ffffff",
         N:"#6b7cff", n:"#f2eee6", S:"#e8e8f0", R:"#ff5c7a", T:"#b8742e", t:"#6e3f16", Y:"#ffd23f", y:"#d19a12", C:"#fff6b0"},
    /* เปลี่ยนร่างตามเลือดที่เหลือ (min = สัดส่วน HP ที่เหลืออย่างน้อย) · dead = ร่างนอนแผ่ + หีบสมบัติ */
    phases:[
      { min:.75, t:"💤 ร่าง 1 · หลับอืด", g:[
    "........................",
    "..................ZZZZ..",
    "....................Z...",
    "..................ZZZZ..",
    "........................",
    ".....................ZZ.",
    "...........NNNNN.....ZZ.",
    "..........NNNNNNNN......",
    "..........NNNN...NNn....",
    ".........NNNNN.....nn...",
    "........nnnnnnnnn.......",
    ".......OOOOOOOOOO.......",
    "......OGGGGGGGGGGO......",
    ".....OLLGGGGGGGGGGO.....",
    "....OGGLGGGGGGGGGGGO....",
    "...OGGGGGGGGGGGGGGggO...",
    "..OGGGEEEGGGGGGEEEGggO..",
    ".OGGGPPGGGGGGGGGGPPGggO.",
    ".OGGGGGGGGGMMMGGGGGGggO.",
    ".OGGGGGGGGGGDGGGGGGGggO.",
    ".OggggggggggDgggggggggO.",
    "..OggggggggggggggggggO..",
    "...OOOOOOOOOOOOOOOOOO...",
    "........................"] },
      { min:.5,  t:"😤 ร่าง 2 · โดนปลุก หงุดหงิด", g:[
    "........................",
    "........................",
    "................nN......",
    "................NN..S.S.",
    "..S.S..........NNN..SSS.",
    "..SSS.........NNNN......",
    ".........OOOOnnnnnn.....",
    ".......OOGGGGGGOO.......",
    "......OGGGGGGGGGGO......",
    ".....OGGGGGGGGGGGGO.....",
    ".....OLLGGGGGGGGggO.....",
    "....OGEEGGGGGGGGGEEO....",
    "...OGGGEEGGGGGGGEEggO...",
    "...OGGEEEEGGGGEEEEggO...",
    "...OGGWWEWGGGGWEWWggO...",
    "..OGGGGWWGGGGGWWGGGggO..",
    "..OGGGGGGGGGGGGGGGGggO..",
    "..OGGGGGGGGGGGGGGGGggO..",
    "..OGGGGGGMMMMMGGGGGggO..",
    "..OGGGGGGMGGGMGGGGGggO..",
    "..OggggggggggggggggggO..",
    "...OggggggggggggggggO...",
    "....OOOOOOOOOOOOOOOO....",
    "........................"] },
      { min:.25, t:"😱 ร่าง 3 · ตกใจ เหงื่อแตก", g:[
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    ".........OOOOOO.........",
    ".......OOGGGGGGOO.......",
    "..D...OGGGGGGGGGGO......",
    "..DD.OGGGGGGGGGGGGO..D..",
    ".....OLLGGGGGGGGggO..DD.",
    "....OGLGGGGGGGGGGggO....",
    "....OGWWWWGGGGWWWWgO....",
    "...OGGWEEWGGGGWEEWggO...",
    "...DGGWEEWGGGGWEEWggO...",
    "...OGGWWWWGGGGWWWWggO...",
    "..OGGGGGGGGGGGGGGGGggO..",
    "..OGGGGGGGGMMGGGGGGggO..",
    "..OGGGGGGGMMMMGGGGGggO..",
    "..OgggggggMMMMgggggggO..",
    "...OgggggggMMgggggggO...",
    "...OGOOOOOOOOOOOOOGO....",
    "...OGO............O.....",
    "....O..................."] },
      { min:0,   t:"🫠 ร่าง 4 · ละลายแล้ว", g:[
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "....D...................",
    "...................D....",
    ".......OOOOOOOOOO.......",
    ".....OOGGGGGGGGGGOO.....",
    "....OGGGGGGGGGGGGGGO....",
    "...OGGLGGGGGGGGGGGGGO...",
    "..OGGGWWWGGGGGGWWWGggO..",
    "..OGGGWEWGGGGGGWEWGggO..",
    ".OGGGGDGGGGGGGGGGGDGggO.",
    ".OGGGGDGGGGMMGGGGGDGggO.",
    ".OggggggggMggMggggggggO.",
    "..OggggggggggggggggggO..",
    "..OGOOOOOGOOOOOGOOOOGO..",
    "..OGO....O....OGO...O...",
    "...O...........O........"] }],
    dead:[
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "................C.......",
    "...............CCC...C..",
    "................C.......",
    "........................",
    ".....SSS....Y........yY.",
    "....SESES.....OOOOOOO...",
    "....SSSSS....OtttttttO..",
    "....S.S.S...OtTTTTTTTtO.",
    "...........COtTTTYTTTtO.",
    ".....S......OOOOOOOOOOO.",
    "............OYCYyYYCyYOC",
    "...OOOOOOO..OYYyYYYyYYO.",
    "..OGGGGGGGO.OOOOOOOOOOO.",
    ".OGLLGGGGGGOOTTTTTTTTTO.",
    "OGELEGGGEGEGOYYYYOYYYYO.",
    "GGGEGGGGGEGGOTTTOYOTTTO.",
    "ggEgEgRgEgEgOTTTTTTTTTO.",
    "OggggRRgggggOOOOOOOOOOO.",
    ".OOOOOOOOOOO............"] },
  { k:"skull", n:"ราชาผู้ไม่กล้ากดปล่อย", e:"💀", anim:"",
    pal:{K:"#f2eee6", k:"#b8b0a4", G:"#ffcc4d", R:"#ff3b5c", E:"#3a0a4a", P:"#c4b5ff", p:"#7a5cd6"},
    g:[
    "....G...G...G...G...G...",
    "....GGGGGGGGGGGGGGGGG...",
    "....GGGRGGGGGGGGGRGGG...",
    "....GGGGGGGGGGGGGGGGG...",
    ".....OOOOOOOOOOOOOOO....",
    "....OKKKKKKKKKKKKKKKO...",
    "...OKKKKKKKKKKKKKKKKKO..",
    "...OKKKEEEKKKKKEEEKKKO..",
    "...OKKKEEEKKKKKEEEKKKO..",
    "...OKKKKKKKKEKKKKKKKKO..",
    "...OKKKKKKKEEEKKKKKKKO..",
    "....OKKKKKKKKKKKKKKKO...",
    ".....OkKOKOKOKOKOKkO....",
    "......OOOOOOOOOOOOO.....",
    ".....OPPPPPPPPPPPPPO....",
    "....OPPPPPPPPPPPPPPPO...",
    "...OPPPPPpKKKKKpPPPPPO..",
    "...OPPPPPpKKKKKpPPPPPO..",
    "...OPPPPPPPPPPPPPPPPPO..",
    "...OPPPPPPPPPPPPPPPPPO..",
    "...OpppppppppppppppppO..",
    "...OOOOOOOOOOOOOOOOOOO..",
    "........................",
    "........................"]}
];
const BOSS_W = 24, BOSS_H = 24;
const bossSkin = k => BOSS_SKINS.find(s=>s.k===k) || BOSS_SKINS[0];
/* ร่างตามเลือดที่เหลือ · frac = HP ที่เหลือ / HP เต็ม (ไม่ส่ง = ร่างแรก) */
function bossPhase(k, frac){
  const sk = bossSkin(k);
  if(!sk.phases) return null;
  return sk.phases.find(p => (frac==null ? 1 : frac) >= p.min) || sk.phases[sk.phases.length-1];
}
function bossGrid(sk, state, frac){
  if(state==="dead" && sk.dead) return sk.dead;
  return sk.phases ? bossPhase(sk.k, frac).g : sk.g;
}

/* วาดบอสเป็น SVG · state: idle | hurt (HP ≤ 30%) | dead
   บอสที่มีร่างตาย (dead) ของตัวเอง จะไม่ถูกกลับหัว/ทำสีเทา แต่โชว์ร่างนอนแผ่ + สมบัติแทน */
function bossSprite(k, px=4, state="idle", frac){
  const sk = bossSkin(k), g = bossGrid(sk, state, frac);
  const pal = Object.assign({O:"#0b0316"}, sk.pal);
  if(state==="hurt") pal.E = "#ff2d55";             // ตาแดงตอนใกล้ตาย
  let body="", anim="", x0=0, y0=0, x1=BOSS_W-1, y1=BOSS_H-1;
  if(state==="dead" && sk.dead){ x0=BOSS_W; y0=BOSS_H; x1=0; y1=0;      // ครอปร่างตายให้พอดีเนื้อหา
    for(let y=0;y<BOSS_H;y++) for(let x=0;x<BOSS_W;x++) if(pal[g[y][x]]){ x0=Math.min(x0,x); y0=Math.min(y0,y); x1=Math.max(x1,x); y1=Math.max(y1,y); } }
  for(let y=y0;y<=y1;y++) for(let x=x0;x<=x1;x++){
    const ch=g[y][x], c=pal[ch]; if(!c) continue;
    const r=`<rect x="${(x-x0)*px}" y="${(y-y0)*px}" width="${px}" height="${px}" fill="${c}"/>`;
    if(sk.anim.includes(ch)) anim+=r; else body+=r;
  }
  const W=(x1-x0+1)*px, H=(y1-y0+1)*px;
  return `<svg class="bossSprite ${state}${state==="dead"&&sk.dead?" own":""}" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" shape-rendering="crispEdges">
    ${body}${anim?`<g class="banim">${anim}</g>`:""}</svg>`;
}
/* วาดลง canvas (การ์ดสรุป / แชร์) */
function drawBossCanvas(ctx, x, y, px, k, state, frac){
  const sk = bossSkin(k), g = bossGrid(sk, state, frac), pal = Object.assign({O:"#0b0316"}, sk.pal);
  for(let yy=0;yy<BOSS_H;yy++) for(let xx=0;xx<BOSS_W;xx++){
    const c=pal[g[yy][xx]]; if(!c) continue;
    ctx.fillStyle=c; ctx.fillRect(x+xx*px, y+yy*px, px, px);
  }
}

/* หีบสมบัติหลังบอส: ปิด = ยังไม่ล้ม · เปิด = ตัดมาจากร่างตายของสไลม์ (พาเลตเดียวกัน) */
const CHEST_PAL = {O:"#0b0316", T:"#b8742e", t:"#6e3f16", Y:"#ffd23f", y:"#d19a12", C:"#fff6b0"};
const CHEST_CLOSED = [
  "...........",
  "...........",
  ".OOOOOOOOO.",
  "OtttttttttO",
  "OtTTTTTTTtO",
  "OOOOOOOOOOO",
  "OTTTTTTTTTO",
  "OYYYYOYYYYO",
  "OTTTOYOTTTO",
  "OTTTTTTTTTO",
  "OOOOOOOOOOO"];
const CHEST_OPEN = [
  ".OOOOOOOO..",
  "OttttttttO.",
  "OtYttttYtO.",
  "OOOOOOOOOO.",
  "OyYCYYyYCO.",
  "OYYYyYYYYO.",
  "OOOOOOOOOO.",
  "OTTTTTTTTO.",
  "OYYYYYYYYO.",
  "OTTTOOTTTO.",
  "OTTTOYTTTO.",
  "OOOOOOOOOO."];
function chestSprite(px=6, open=false){
  const g=open?CHEST_OPEN:CHEST_CLOSED, W=11, H=g.length; let body="";
  for(let y=0;y<H;y++) for(let x=0;x<W;x++){ const c=CHEST_PAL[g[y][x]]; if(c) body+=`<rect x="${x*px}" y="${y*px}" width="${px}" height="${px}" fill="${c}"/>`; }
  return `<svg class="chestSprite" width="${W*px}" height="${H*px}" viewBox="0 0 ${W*px} ${H*px}" shape-rendering="crispEdges">${body}</svg>`;
}
